### ISSUE TITLE
Governance Committee

### ISSUE THREAD

**Issue by emily878** [centerforgov/open-data-getting-started#4]
Reviewing this is bringing up something I hadn't thought of before, but I think it would be a really helpful distinction - a governance committee for getting started with an open data program (strategic and policy staff) vs. governance of the ongoing open data program (program staff with some policy oversight). Do you think it would be useful to find a way to distinguish these governance aspects? I can come up with a few lines on this if so.

**Comment by nghadji** [comment]
You are right, there is a distinction. Do you think this section needs to cover both distinctions in detail, or just the governance of the ongoing program? Cities will vary in their procedures for initiating a new program, and I don't think we want to specify they way in which it's initiated, but making the distinction is still a good idea. Feel free to add that language as needed, thanks.
