### ISSUE TITLE
Suggestions for Modifying Technology Choice Section

### ISSUE THREAD

**Issue by mheadd** [centerforgov/open-data-getting-started#8]
In reading through the section on [technology choice](https://github.com/centerforgov/open-data-getting-started/blob/master/selecting-the-right-technology.md), there seems to be a predisposition for what is described as "complex" open data portals.

As it currently reads - `cities tend to start simple ... and then move towards advanced platforms` - the suggestion is that (by definition) mature open data programs have complex open data sites and immature ones do not. 

For some governments - particularly those that are smaller or that have budget constraints - the "simple" open data portal might be an appropriate end state. [Albuquerque](https://www.cabq.gov/abq-data/) - which is cited as an example in other parts of the guide - is a well known example but there are others. Though not a city government, the [State of Delaware](http://delaware.gov/topics/data.shtml) has used a "simple" open data site for several years. 

In addition, it seems like the driver for migrating from a simple to a more complex open data site should be driven by user needs - the guide doesn't offer much in the way of guidance on what factors should motivate this move. In other words, "you should consider migrating to a more complex site if your users are specifically asking you for things that you can't get without using a more sophisticated platform."

**Comment by technickle** [comment]
Added an adaptation of this language to the technology section. Thanks for the input @mheadd!

**Comment by mheadd** [comment]
:+1:
